version: '3.8'
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Str0ngP@ss!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app_network


  bookstoreserver:
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - app_network
    volumes:
      - .:/app  
      - ~/.nuget/packages:/root/.nuget/packages 
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=BookStore;User Id=sa;Password=Str0ngP@ss!;Encrypt=False;TrustServerCertificate=True;
      - DOTNET_MODIFIABLE_ASSEMBLIES=Debug
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - sqlserver
      
networks:
  app_network:
    driver: bridge
