version: '3.8'

services:
  app:
    build: 
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=YourDatabase;User Id=sa;Password=Ss0583220307;
    ports:
      - "5000:5000"

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "Ss0583220307"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      /bin/bash -c "sleep 20 && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Ss0583220307 -i /docker-entrypoint-initdb.d/init.sql"
    healthcheck:
       test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Ss0583220307", "-Q", "SELECT 1"]
       interval: 10s
       retries: 5
       start_period: 10s
       timeout: 3s

volumes:
  sql_data:
